### ISSUE TITLE
Header 구현

### ISSUE THREAD

**Issue by mj0107** [1119-Blog/frontend#2]
### 📄 Describe
**로그인 했을 시에 보이는 Header를 구현합니다.**

### ✅ Tasks
- [ ] 로그인 상태 전역 관리
- [ ] 회원 Header UI 컴포넌트 구현
- [ ] 비회원 Header UI 컴포넌트 구현
- [ ] 메뉴 라우팅 설정
- [ ] Fixed 설정
- [ ] 보호 라우팅 설정

### 🙋🏻 More

Link : https://www.notion.so/given-dragon/API-6f26edbc7be04845ab4a9f2e9c33db92
